### ISSUE TITLE
Derecho e Izquierdo la primera vez

### ISSUE THREAD

**Issue by edisonperez** [edisonperez/gwybio#11]
Cuando se verifica una persona que no está en la BD local, siempre pide el dedo derecho y luego el izquierdo, y la respuesta es NO HIT. 

Sólo debe verificar con uno de los dos.

**Comment by johnsevillano** [comment]
Indicar en que prueba
Extranjeros , Nacional?

**Comment by edisonperez** [comment]
Nacional

**Comment by edisonperez** [comment]
Nacional, DNI 41460156

**Comment by edisonperez** [comment]
Versión actualizada
