### ISSUE TITLE
Error en la validación de un CE

### ISSUE THREAD

**Issue by edisonperez** [edisonperez/gwybio#14]
Cuando se envía un carné de extranjería, que tiene menos de 8 dígitos, está devolviendo un error de validación: 
``-4:Tamaño de campo <<DOC IDENTIDAD>> es incorrecto`` 

La validación de 8 dígitos únicamente es para los tipos de documento L (DNI).

**Comment by johnsevillano** [comment]
Enviar la cadena completa de parametros que se le pasan al jar client

**Comment by edisonperez** [comment]
```
echo VALIDAR_EXTRANJERO E 1234 1 36 41460156 118.216.51.96 P113022 IW9H 0 NONE 1 NONE 0241 1 | exec /opt/java/bin/java -jar /opt/nacar/biometrico/ClienteWSRPCEclipse.jar
```

**Comment by johnsevillano** [comment]
Verificar la cantidad de parámetros que se le pasan al jar cliente son solo 14 , pero se le están pasando 15.

**Comment by johnsevillano** [comment]
El valor que se esta pasando al parámetro tipValidacion, no es 1 sino 3

**Comment by edisonperez** [comment]
Considerar el campo DNI_AUTORIZADO como input, de forma tal que la interfaz no cambie por método, y sólo cambien los valores que se envían. 
Si bien es cierto no es mandatorio para la verificación, se puede enviar y guardar en la BD (para posterior seguimiento).

**Comment by johnsevillano** [comment]
Atendido se actualizo el jar cliente y los métodos validar_nacional, validar_extranjero y enrolar tiene la misma cantidad de parámetros de entrada.
