### ISSUE TITLE
Respuesta HIT: Demo Demo Demo

### ISSUE THREAD

**Issue by edisonperez** [edisonperez/gwybio#15]
Cuando se envió un DNI que no existía en la BD, la respuesta fue un HIT (pese a que dicho DNI no existe en la BD de TEST), y los nombres y apellidos fueron Demo Demo Demo. 
El comando: 
```
echo VALIDAR_NACIONAL L 45069256 1 36 41460156 118.216.51.96 P113022 IW9H 0 NONE 1 NONE 0241 1 | exec /opt/java/bin/java -jar /opt/nacar/biometrico/ClienteWSRPCEclipse.jar > /opt/nacar/tmp/36/lector-biometrico-output.txt
```

**Comment by johnsevillano** [comment]
verificar que en el archivo BioGatewayRPCWS.properties
el parámetro:  loopback no este establecido a 1
el archivo en mención se encuentra en la ruta : $ZY_HOME/conf/BioGatewayRPCWS
enviar logs de cliente y servidor para verificar.
