### ISSUE TITLE
No guarda cliente

### ISSUE THREAD

**Issue by edisonperez** [edisonperez/gwybio#16]
Cuando se envió un DNI que no existe en la tabla CLIENTES, la respuesta es un HIT (pese a que dicho DNI no existe en la BD de TEST), y los nombres y apellidos son vacíos. 

Tampoco se guarda al final. 

El comando: 
```
echo VALIDAR_NACIONAL L 45069256 1 36 41460156 118.216.51.96 P113022 IW9H 0 NONE 1 NONE 0241 1 | exec /opt/java/bin/java -jar /opt/nacar/biometrico/ClienteWSRPCEclipse.jar > /opt/nacar/tmp/36/lector-biometrico-output.txt
```

**Comment by johnsevillano** [comment]
verificar que en el archivo BioGatewayRPCWS.properties
el parámetro: loopback no este establecido a 1, ya que este valor indica que el Gateway realizara un proceso loopback es decir simulara la conexión a RENIEC dando HIT a las transacciones y los valores que se muestran al jar cliente son demo demo demo. Se ha registrado en la tabla clientes porque primero hay HIT, y luego no existen los valores de Apellidos y Nombre porque fue un requerimiento de BBVA , esta configuración solo es para propósitos de pruebas y no debe estar configurada en un ambiente productivo. 
El archivo en mención se encuentra en la ruta : $ZY_HOME/conf/BioGatewayRPCWS
enviar logs de cliente y servidor para verificar.

El valor de loopback debe ser 0.
Con ello el gateway va a RENIEC cuando realizar la validación de identidad.

**Comment by edisonperez** [comment]
¿Es necesario reiniciar el servidor (Gateway Biométrico)?
¿Es necesario reiniciar el cliente a RENIEC?

**Comment by johnsevillano** [comment]
¿Es necesario reiniciar el servidor (Gateway Biométrico)? SI
¿Es necesario reiniciar el cliente a RENIEC?, El servicio BioGatewayService.jar no es necesario.
