### ISSUE TITLE
Error durante validación sin biometría

### ISSUE THREAD

**Issue by edisonperez** [edisonperez/gwybio#18]
Cuando se ejecuta lo siguiente

```
echo VALIDAR_NACIONAL L 41192371 1 03 41460156 118.216.51.96 P020530 ZI03 0 NONE 1 NONE 0241 1 NONE | exec /opt/java/bin/java -jar /opt/nacar/biometrico/ClienteWSRPCEclipse.jar > /opt/nacar/tmp/03/lector-biometrico-output.txt
```

NO DEBE SOLICITAR LA HUELLA. Actualmente está solicitando la huella para validación. Como se puede ver, se está enviando en el campo 15 (notificación) del método VALIDAR_NACIONAL el valor 1 (SIN BIOMETRIA).

**Comment by johnsevillano** [comment]
Atendido con actualización del ear.
