### ISSUE TITLE
HIT sin nombres

### ISSUE THREAD

**Issue by edisonperez** [edisonperez/gwybio#19]
Se ejecuta la siguiente consulta 

```
echo VALIDAR_NACIONAL L 41460156 1 36 41460156 118.216.51.96 P113022 IW9H 0 NONE 1 NONE 0241 2 NONE | exec /opt/java/bin/java -jar /opt/nacar/biometrico/ClienteWSRPCEclipse.jar > /opt/nacar/tmp/36/lector-biometrico-output.txt
```

y el resultado no trae los datos de la persona, pese a que en la BD sí se guardaron los nombres y apellidos. 

``` 
1
70006
HIT: Persona Identificada
8000
8000: Todas las operaciones se efectuaron correctamente





0
VERIFICAR EN DNI
0
9419#36944
```

**Comment by johnsevillano** [comment]
Se esta revisando, en breve se actualizara el link del ear. Se notificara por mail para la descarga.

**Comment by johnsevillano** [comment]
Ya se actualizo el ear , por favor hacer la descarga y el despliegue correspondiente , 
http://dev.zytrust.com/submit/bbva/2da/extranjeros/server/ear/BioGatewayRPCWSEAR1_BBVA_FINAL_EXT_WSQ_DNIe_SB.ear
y realizar las pruebas
Nota: Puedes verificar que se haya desplegado el ultimo ear en el WAS , porque debe existir una linea en el log de la aplicación (ZTLog.log)
Indicando la siguiente cadena de texto: "BioGatewayRPCWS V2015 - v2 - compiled 08052015"
