### ISSUE TITLE
Error al enviar el tipo de operacion

### ISSUE THREAD

**Issue by edisonperez** [edisonperez/gwybio#21]
Cuando se realiza la invocación con el parámetro tipo de operación: 
```
echo VALIDAR_NACIONAL L 41192371 1 36 41460156 118.216.51.96 P020530 IW9H 0 NONE 1 RTA 0241 1 NONE | exec /opt/java/bin/java -jar /opt/nacar/biometrico/ClienteWSRPCEclipse.jar > /opt/nacar/tmp/36/lector-biometrico-output.txt
```

Se obtiene el mensaje 
`-24:El campo <<TIPO OPERACIóN>> es incorrecto`

**Comment by johnsevillano** [comment]
Se esta enviando al jar cliente, como parametro: tipo operación la cadena  "RTA", según el modelo que tenemos esto corresponde al campo DE_TIPO_OPERACION , sin embargo lo que se esperaba era un valor numérico (CO_TIPO_OPERACION), por ello el jar cliente esta reportandolo como no valido.
Si se va a enviar este valor, se debe hacer un cambio a nivel del jar cliente y gateway biometrico que estamos actualizando.

**Comment by johnsevillano** [comment]
Se indican las aplicaciones actualizadas:

1. jar cliente 
http://dev.zytrust.com/submit/bbva/2da/extranjeros/cliente_nacar/ClienteWSRPCEclipse.jar

2. ear GatewayBiometrico
http://dev.zytrust.com/submit/bbva/2da/extranjeros/server/ear/BioGatewayRPCWSEAR1_BBVA_FINAL_EXT.ear

3. Script DB
http://dev.zytrust.com/submit/bbva/2da/extranjeros/server/bd/actualizar.sql

Nota: El Gateway Biometrico requiere que se ejecuten previo al deploy de esta nueva versión, los querys para agregar el nuevo campo y actualizar los registros de la tabla:

/*1. Modificación de la Tabla IBTR_TIPO_OPERACION */

ALTER TABLE IBTR_TIPO_OPERACION
  ADD DE_LAR_TIPO_OPERACION VARCHAR2(50); 

/* 2. Actualización de registros Tabla IBTR_TIPO_OPERACION */

UPDATE IBTR_TIPO_OPERACION 
SET DE_LAR_TIPO_OPERACION = 'Retiro con tarjeta'
WHERE CO_TIPO_OPERACION = 4
  
UPDATE IBTR_TIPO_OPERACION 
SET DE_LAR_TIPO_OPERACION = 'Retiro sin tarjeta'
WHERE CO_TIPO_OPERACION = 3

UPDATE IBTR_TIPO_OPERACION 
SET DE_LAR_TIPO_OPERACION = 'Cobro de cheque'
WHERE CO_TIPO_OPERACION = 1

UPDATE IBTR_TIPO_OPERACION 
SET DE_LAR_TIPO_OPERACION = 'Ninguna Operación'
WHERE CO_TIPO_OPERACION = -1

IBTR_TIPO_OPERACION. Si no se realiza esta tarea pueden generarse errores en la aplicacion gateway que se reporten erróneamente como bugs de la aplicación.
