### ISSUE TITLE
Error no controlado

### ISSUE THREAD

**Issue by edisonperez** [edisonperez/gwybio#5]
Cuando se da un error no controlado, el código de respuesta es 0 y el mensaje es: 
`8002: Ocurrió una excepción try catch`

Cuando debería ser un mensaje más acorde al error producido. 
Además de ello, el cero en la primera línea no corresponde a un NO-HIT, ni a algún código de error de RENIEC. 

```
0


8002
8002: Ocurrió una excepción try catch







0
9008#36007
```

**Comment by jmiraval** [comment]
Según la estructura que nos enviaron, en los códigos que se especifican:
- Código de error RENIEC
- Código de error
El código 0 representa un NO HIT u otro error, es necesario que nos especifiques el valor del retorno para el caso del  try catch.

**Comment by edisonperez** [comment]
En el documento se especifica que 0 es NO HIT, 
Actualizar el documento e indicar que también corresponde a otro error. Cambiar el mensaje por algo como "Ocurrió un error interno a nivel de aplicación, Contactar con el Soporte Técnico". 

Validar que este mensaje de excepción try catch no reemplace otros como el 8020, 8018, 8011.

**Comment by johnsevillano** [comment]
Se ha actualizado el documento "ESPECIFICACIÓN TÉCNICA PARA EL CLIENTE(JAR) GATEWAY BIOMÉTRICO", para aclarar que el valor 0 de indResultado , significa NO HIT o ERROR , para mayor descripción, debe verificar los valores de bioCodErrorReniec.
Se va a cambiar el mensaje por el indicado  "Ocurrió un error interno a nivel de aplicación, Contactar con el Soporte Técnico".
