### ISSUE TITLE
Almacenamiento de huellas en formato WSQ

### ISSUE THREAD

**Issue by edisonperez** [edisonperez/gwybio#6]
Según lo requerido, el formato de almacenamiento debe ser WSQ. 
Adicionalmente, en la tabla `IBTV_MOVIMIENTO`:
- Se almacenan valores en las columnas `BL_WSQ_DER` y `BL_WSQ_IZQ`, que no son formato WSQ
- Algunas de las columnas `BL_WSQ_DER` y `BL_WSQ_IZQ` tienen tamaño 1.

**Comment by johnsevillano** [comment]
Se ha actualizado el documento de  Modelo de Datos con las observaciones que nos hicieron llegar, en este documento se especifican dos campos adicionales sobre la tabla IBTV_MOVIMIENTO en las cuales se almacenaran las huellas(BL_WSQ_DER y BL_WSQ_IZQ en formato WSQ) y las plantillas (BL_TEMPLATE_DER y BL_TEMPLATE_IZQ formato Morpho).
Asi mismo se ha actualizado el Gateway Biometrico para eliminar las columnas blob empty.
