### ISSUE TITLE
Archivo log no se fracciona

### ISSUE THREAD

**Issue by edisonperez** [edisonperez/gwybio#7]
El archivo /opt/nacar/biometrico/ClienteWSRPCEclipse.log no se está fraccionando según el tamaño. 

Se debe corregir el archivo `ZT.properties`.

**Comment by johnsevillano** [comment]
Se ha corregido el archivo log. A continuación se indica el propertie del logger corregido.

Obs: En la linea log4j.appender.jarclient.File=ClienteWSRPCEclipse.log, se debe 
colocar la ruta correcta del archivo log ,en donde se tiene permitido guardar los logs(ver cual es el valor que tiene ese campo en el actual propertie : ZT.properties)
ejemplo: /tmp/ClienteWSRPCEclipse.log 

log4j.rootLogger= ,jarclient

# ***** R is set to be a RollingFileAppender.
log4j.appender.jarclient=org.apache.log4j.RollingFileAppender
log4j.appender.jarclient.File=ClienteWSRPCEclipse.log
log4j.appender.jarclient.Append=true

# Global Threshold - overridden by any Categories below.
#DEBUG, INFO, WARN, ERROR, FATAL
log4j.appender.jarclient.Threshold=DEBUG

# ***** Max file size is set to 500KB
log4j.appender.jarclient.MaxFileSize=1MB

# ***** Keep one backup file
log4j.appender.jarclient.MaxBackupIndex=5

# ***** R uses PatternLayout.
log4j.appender.jarclient.layout=org.apache.log4j.PatternLayout
log4j.appender.jarclient.layout.ConversionPattern=%-5p [%d{dd/MMM/yyyy HH:mm:ss}] %C(%M)/line:%L===> %m%n

log4j.appender.jarclient.ImmediateFlush=true
